// Copyright (c) 2024 John Yoon. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for more information.
//
// This is a theme file for YouTube Downloader Application.
//
// [THEME INFO]
//     contains metadata about the theme.
// [THEME VARIABLES]
//     contains variables that can be used in this theme file only.
//     these variables will be substituted in the theme colors and
//     additional styles. Use ${variable} to refer to the variable.
// [THEME COLORS]
//     contains color variables that can be used in the theme.
//     these variables are used in both core theme of the
//     application and the additional styles, so DO NOT
//     MODIFY THE NAME OF THESE VARIABLES.
//
//     Their values can be modified as theme colors.
//
//     Use ${variable} to refer to the variable.
// [ADDITIONAL STYLES]
//     contains additional styles that can be used in the theme.
//
//     Use ${variable} to refer to the variable defined in theme
//     variables and theme colors sections.
//
//     This section follows qss syntax (https://doc.qt.io/qt-6/stylesheet-syntax.html)
//     and will have highest priority over any other styles defined
//     in the system (including the core styles).
//
// SPECIAL VARIABLES:
//     Apart from the variables defined in the theme colors section,
//     There are special variable types and syntaxes that can be used
//      - ${font-size}
//            the font size of the application
//      - ${font-size:+n}
//            the font size of the application + n where n is an integer
//      - ${font-size:-n}
//            the font size of the application - n where n is an integer
//      - ${resource:path/to/resource}
//            the path to the resource file

[THEME INFO]
name: system light
author: John Yoon
version: 2.1.0

[THEME VARIABLES]
theme-green: #4CAF50
theme-light-green: #61C464
theme-dark-green: #439A45
theme-red: #FF5252
theme-light-red: #FF7575
theme-dark-red: #E04848
theme-blue: #2196F3
theme-light-blue: #42A5F5
theme-dark-blue: #1976D2
theme-fade-1: #FFFFFF // 255
theme-fade-2: #F0F0F0 // 240
theme-fade-3: #E1E1E1 // 225
theme-fade-4: #C3C3C3 // 195
theme-fade-5: #B4B4B4 // 180
theme-dark-1: #000000 // 0
theme-dark-2: #0F0F0F // 15
theme-dark-3: #1E1E1E // 30
theme-dark-4: #2D2D2D // 45
theme-dark-5: #3C3C3C // 60

[THEME COLORS]
primary-color: ${theme-green}
primary-hover-color: ${theme-light-green}
primary-pressed-color: ${theme-dark-green}
primary-text-color: ${theme-fade-1}
secondary-color: ${theme-blue}
secondary-hover-color: ${theme-light-blue}
secondary-pressed-color: ${theme-dark-blue}
secondary-text-color: ${theme-fade-1}
accent-color: ${theme-red}
accent-hover-color: ${theme-light-red}
accent-pressed-color: ${theme-dark-red}
accent-text-color: ${theme-fade-1}
base-background-color: ${theme-fade-2}
base-foreground-color: ${theme-dark-3}
field-background-color: ${theme-fade-1}
border-color: ${theme-fade-3}
placeholder-text-color: ${theme-fade-5}

[ADDITIONAL STYLES]
QComboBox[class="combo-box"]::drop-down {
    border: 0px;
}

QComboBox[class="combo-box"]::down-arrow {
    image: url(${resource:style/assets/icon/combo-box-arrow-down-black.png});
    width: 16px;
    height: 16px;
    margin-right: 15px;
}
